from datetime import date
from streamfinity_fastapi.schemas.movie_actor_schema import ActorInput
from streamfinity_fastapi.schemas.user_schema import UserInput
from streamfinity_fastapi.streamfinity import app
from fastapi import status
from fastapi.testclient import TestClient
client = TestClient(app)
# Test data
test_actor = ActorInput(
    first_name="Test",
    last_name="Actor",
    date_of_birth=date(1990, 1, 1),
    nationality="American",
    biography="Test biography",
    profile_picture_url="https://example.com/test_actor.jpg",
)

# A valid JWT token for testing generated by using a dummy secret key
access_token = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJzdWIiOiJwa2Fsa2llMkBnbWFpbC5jb20iLCJleHAiOjE4NjM1NjkzMDZ9."
    "7_92eJtzh3v0VNBoUJZknyoQI1zxSWIEy_AG12RGmuc"
)


def test_add_actor():
    actor_data = test_actor.dict()
    actor_data["date_of_birth"] = test_actor.date_of_birth.isoformat()
    response = client.post("/api/actors/", json=actor_data,
                           headers={"Authorization": f"Bearer {access_token}"})
    assert response.status_code == status.HTTP_201_CREATED
    assert response.json()["first_name"] == test_actor.first_name
    assert response.json()["last_name"] == test_actor.last_name