apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamfinity-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamfinity-api
  template:
    metadata:
      labels:
        app: streamfinity-api
    spec:
      containers:
      - name: streamfinity-api
        image: a7032181/streamfinity-api:latest # 修改此處
        ports:
        - containerPort: 8000
